services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: chatbot_user
      MYSQL_PASSWORD: chatbot123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
